"""
config.py — Configuration for sync scripts.

All config is loaded from auto-discovered JSON files in the workspace.
These files are generated by discover_workspace.py during setup and
can be re-run anytime to refresh.

Files loaded:
  ~/.openclaw/workspace/discovered_bots.json    — bot UIDs + display name patterns
  ~/.openclaw/workspace/discovered_channels.json — excluded noise channels
  ~/.openclaw/workspace/team.json               — tracked people, priorities, channels
"""

from shared import WORKSPACE, load_json

# ── Auto-discovered config (generated by discover_workspace.py) ─────────────

_bots = load_json(WORKSPACE / "discovered_bots.json")
BOT_UIDS = set(_bots.get("bot_uids", []))
BOT_PATTERNS = set(_bots.get("bot_patterns", []))

_channels = load_json(WORKSPACE / "discovered_channels.json")
EXCLUDE_CHANNELS = set(_channels.get("exclude_channels", []))

# ── Team-specific config (loaded from team.json) ───────────────────────────
# Initially generated by discover_workspace.py, editable post-install.

_team = load_json(WORKSPACE / "team.json")

PRIORITY_CHANNELS = set(_team.get("priority_channels", {}).keys())
PRIORITY_DM_USERS = set(_team.get("priority_dm_users", {}).keys())
TRACKED_PEOPLE = _team.get("tracked_people", {})
DEEP_RECONCILE_PEERS = _team.get("deep_reconcile_peers", {})
CLIENT_CHANNEL_PREFIX = _team.get("client_channel_prefix", "")
CLIENTS = _team.get("clients", {})
